### ISSUE TITLE
Two permission can't use

### ISSUE THREAD

**Issue by hexllo** [hotchemi/PermissionsDispatcher#145]
“android.permission.SYSTEM_ALERT_WINDOW”
“android.permission.WRITE_SETTINGS”
@egor-n 
![image](https://cloud.githubusercontent.com/assets/14800596/15142069/f9af37b4-16d5-11e6-9ef6-8c1e1b03c2fd.png)

**Comment by hotchemi** [comment]
They are special permissions so you can't handle these at the same time. Ordinal permissions can be handled.

**Comment by hexllo** [comment]
OK,Thank for you help;Thank you very much.

**Comment by E3V3A** [comment]
Why not? And how to circumvent this?

**Comment by aurae** [comment]
This is a reaction to AOSP's inconsistent handling of permissions in some places. The permission flow for `SYSTEM_ALERT_WINDOW` doesn't follow the framework's "normal route"; instead PermissionsDispatcher needs to redirect the user to their System Settings to toggle some button. Because of this, we decided not to allow mix-and-matching of this flow with the "Show Runtime Permissions Dialog" flow that usually happens. Working around this, you would need to separate the special permissions from the ordinary ones, and chain them together from two different methods.
