### ISSUE TITLE
If the phone prior to 6.0 do run-time rights management, as well as with this you use it?

### ISSUE THREAD

**Issue by chond** [hotchemi/PermissionsDispatcher#152]
If the phone prior to 6.0 do run-time rights management, as well as with this you use it?

**Comment by hotchemi** [comment]
Sorry what u mean?

**Comment by chond** [comment]
There are some other phones, Before the system is 6.0, But it has done a check permission to run, if you use the framework to check permission, can you check it?

**Comment by aurae** [comment]
Since we're using `PermissionChecker` from the support-v4 library under the hood, we are subject to the same policies enforced by that class, which is the default expected behaviour on the platform. Quoting [its documentation](https://developer.android.com/reference/android/support/v4/content/PermissionChecker.html), it says:

    

> (...) For apps targeting API lower than M these permissions are always granted as such apps do not expect permission revocations and would crash. Therefore, when the user disables a permission for a legacy app in the UI the platform disables the APIs guarded by this permission making them a no-op which is doing nothing or returning an empty result or default error.

It's encouraged to include PermissionsDispatcher into apps that are potentially running on pre-M devices as well, though! However, it doesn't detect potentially revoked permissions automatically (afaik anyways), since that's not the default behaviour of the platform.

**Comment by hotchemi** [comment]
@chond Still having a trouble?
