### ISSUE TITLE
Proguard can't find referenced class FragmentCompat

### ISSUE THREAD

**Issue by muetzenflo** [hotchemi/PermissionsDispatcher#172]
Hi!

In this file: https://github.com/hotchemi/PermissionsDispatcher/blob/master/library/src/main/android/permissions/dispatcher/v13/V13Access.java

you are referencing android.support.v13.app.FragmentCompat
When using your library with ProGuard there are 3 warnings preventing a successful build:

```
permissions.dispatcher.v13.V13Access: 
can't find referenced class android.support.v13.app.FragmentCompat
```

I already tried to add proguard rules like

```
-keep public class android.support.v13.app.FragmentCompat { *; }
-keep public class permissions.dispatcher.v13.** { *; }
```

but to no avail. Do you have any hint, how to get the library to work with proguard?

**Comment by aurae** [comment]
I assume you're not using the support-v13 library in your build? Access to this optional dependency is guarded by this `V13Access` class, and only used if you provide that dependency anyway. If you don't, then ProGuard might get confused since it doesn't understand this case.

You should be able to suppress this warning using:
`-dontwarn permissions.dispatcher.v13.**`

Thanks for bringing this up though, we will consider adding a section on ProGuard rules within the README, or better yet, add them directly into a future release in `consumerProguardFiles`.

**Comment by hotchemi** [comment]
@muetzenflo Could you check https://github.com/hotchemi/PermissionsDispatcher/issues/172#issuecomment-232083699? Currently we've not bundled any proguard rules but it's worth to try :D

**Comment by muetzenflo** [comment]
@aurae Thanks, the dontwarn flag did work. And yes: A proguard-section in the readme is always nice! :+1:

**Comment by shiraji** [comment]
So, basically following tasks to do.

add following code in build.gradle

```gradle
defaultConfig {
    consumerProguardFiles 'proguard-rules.txt'
}
```

create new file called proguard-rules.txt

```
-dontwarn permissions.dispatcher.v13.**
```

Do we still need README's proguard section? Maybe just say "Don't worry! you can use proguard without any setting for this library!"

Let me reopen this issue.

**Comment by aurae** [comment]
Mentioning that ProGuard is taken care of in the README is a good move, I would say. And yes, the rest is exactly as you described!

**Comment by muetzenflo** [comment]
I agree with aurae. From a developers point of view it's always nice to have ProGuard information in the readme. It's just a few lines that make things clear upfront.
