### ISSUE TITLE
Can't set more the one permission check at same flow

### ISSUE THREAD

**Issue by ktasl** [hotchemi/PermissionsDispatcher#233]
If I want check Location, Phone and Storage permission on same Activity's onCreat(),
it always show one permission check: Location, and won't show phone and storage permission check.

**Comment by aurae** [comment]
Have you annotated the method properly, so that the `@NeedsPermission` has all three in it? The Android framework only prompts for permissions that haven't already been granted, so please also make sure that the app wasn't accidentally given Storage and Phone permissions by looking within its Settings page. Finally, I don't have the list of dangerous permissions in front of me right now, but it might even be the case that Phone isn't a dangerous permission?

**Comment by hotchemi** [comment]
@ktasl Can you ask on stackoverflow or give us a sample that we can reproduce the problem?

**Comment by hotchemi** [comment]
Please reopen if needed.
