### ISSUE TITLE
Pre-request hook.

### ISSUE THREAD

**Issue by shbi** [hotchemi/PermissionsDispatcher#246]
Requesting a Hook to be called before a request is made.

On MarshMellow in particular SYSTEM_ALERT_WINDOW overlays will prevent requests from being fulfilled.

What would be nice is a method that gets called just before requesting a permission, giving the author a chance to disable some of these things before the request so they do not block it.

**Comment by hotchemi** [comment]
@shbi Thx for your request. Actually I'm not sure the problem that you're facing but we can deal with such a thing before calling `WithCheck` method by developers side as of now right?

**Comment by shbi** [comment]
This is i am having right now is we are using SYSTEM_ALERT_WINDOW permission to provide an always available menu. This menu can prevent permissions from being granted on Marshmellow. Nougat is fine since the OS handles removing these overlays before displaying the permissions dialog. What I want is to do this on Marshmellow devices (they are about 90% of the devices running this app currently)

I have tried removing the overlay before calling withcheck and then adding it back when the result is returned. Problem is, if the permission was already granted, the result is never returned.

So now i have to check for the permission and if it;s not there remove overlay and call with check, otherwise just call the method directly. Which defeats some of the purpose of this.

Some kinda of "BeforeRequest" hook to perform some set up would be nice.

**Comment by hotchemi** [comment]
Thx for your giving us a detail. I understood the problem but unfortunately we'll not provide such a hook point.
The reason is as you said that's request is certainly a niche. We'd like to value the existing 5 annotations and don't wanna confuse users by adding more endpoint(we believe simple is the best).
And if I remember correctly you already deal with the problem by handling your side right? So I'd like to delegate such a work to users.
Anyway, thx for your interesting feature request and discuss. Please keep using the library and give us your thoughts again🙇

**Comment by shbi** [comment]
Thanks, this doesn't really server my needs if I need to implement half of it  my self just to handle this situation.
