### ISSUE TITLE
Can we remove native fragment hack?

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#254]
### Overview

We've been dealing with native fragment by getting `support-v13` dependency existence on runtime.
It's a snappy idea but on the other hand we came across the problem(https://github.com/hotchemi/PermissionsDispatcher/issues/220) and it turned out it's a little bit hacky and not easy to grasp for me.
After investigating the AOSP source code below I found that every fragment needs to be attached to Activity and I just came up with it seems being possible to delegate the work to ActivityCompat.

Actually I'm not sure the FragmentCompat detail yet but what do you think guys @aurae @shiraji ?

ref: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v13/java/android/support/v13/app/FragmentCompat.java#58

**Comment by aurae** [comment]
The thing that's tying us to `FragmentCompat` is the fact that, if we used `ActivityCompat` instead, we would probably break the callback chain for the `Fragment`. You wouldn't get the call to `Fragment#onRequestPermissionsResult()`, because that would only be called on the `Activity` that we're attached to.

I personally think that the optional dependency on `support-v13` is fine the way it is, I'm just unable to piece together what's on the classpath used by Jack during the runtime of annotation processors.

**Comment by hotchemi** [comment]
Ah sorry for leaving the issue for a long time...let me put my newest thought on it later.

**Comment by hotchemi** [comment]
Well, that'd be an another problem so let me close the issue and create another one.
