### ISSUE TITLE
PermissionsDispatcher makes wrong class hierarchy

### ISSUE THREAD

**Issue by nao20010128nao** [hotchemi/PermissionsDispatcher#262]
When I set @RuntimePermission and related annotations in the nested class, PermissionDispatcher generates classes with wrong class hierarchy.    
If there's a code like this,
```
package test;
public class Test {
  //Not an Activity
  @RuntimePermission
  public static class NestedActivity extends AppCompatActivity {
    //An Activity
    @NeedsPermission("android.permission.ACCESS_FINE_LOCATION")//Some permissions for this method
    public void permissionRequiredMethod(){
       //Some code here
    }
  }
}
```
From this code, PermissionDispatcher generates a code like this:
```
package test.Test;
public class NestedActivityPermissionDispatcher{
  //Generated code here
}
```
This generated code makes some error where referencing Test class and package-private methods in generated code. (This error doesn't happen at my code.)    
    
I think generated code must be like this to work correctly:
```
package test;
public class Test$NestedActivityPermissionDispatcher{
  //Generated code here
}
```

**Comment by shiraji** [comment]
Interesting.

Just curiosity, why do you need to write Activity as nested class?

**Comment by shiraji** [comment]
Do we really need `Test$` prefix?

**Comment by shiraji** [comment]
If someone confirm no prefix needed, I would send PR for this issue.

**Comment by nao20010128nao** [comment]
> Just curiosity, why do you need to write Activity as a nested class?    

It is actually Fragment in my code. :)   

> Do we really need Test$ prefix? It's just a name of the class. I believe the following code still works.

Yeah, prefix may not be needed in this case.    
I only wanted it to work in the nested class.

**Comment by hotchemi** [comment]
@nao20010128nao @shiraji 
Sorry for the late and thx for your contribute and report.
Well, I suppose there's no value to define nested Activity/Fragment inside of a class...because it always bring a risk to cause memory leak or something like that right? If so I'm not for the change that leads user to allow a wrong approach.
Could you tell me why nested definition is needed?

**Comment by nao20010128nao** [comment]
@hotchemi Because I need to put some Fragments in a Java file to look for classes quickly and code faster.    
I know that it is usual to make a Java file per a class, but it sometimes make me confused while coding.

**Comment by aurae** [comment]
I can relate to the use case for nested Fragment classes within Activities that are otherwise pretty barebones - I apply this same pattern with PreferenceFragmentCompat, for instance. It's not a memory leak issue if the nested class doesn't have any outer reference, I.e. if it is declared static.
Thanks for your report, @nao20010128nao! Shiraji-san has started working on adding support for this already.

**Comment by hotchemi** [comment]
Hmm, okay you've solved me. I've never tried such a usage though:D
