### ISSUE TITLE
How  can i use this to add a permission to a activity ,but not a onclicklistener?

### ISSUE THREAD

**Issue by litianyuan1111** [hotchemi/PermissionsDispatcher#265]

**Comment by hotchemi** [comment]
Sorry I can't understand what you mean. Please see sample module and ask something on stack overflow if you're stuck. https://github.com/hotchemi/PermissionsDispatcher/tree/master/sample

**Comment by litianyuan1111** [comment]
in your sample ,PermissionsDispatcher  in onclick method,but i want show get permission and don`t current the main thread.

**Comment by hotchemi** [comment]
@litianyuan1111 Sorry I don't understand what you mean.

**Comment by aurae** [comment]
If I understand correctly, you want to request a Runtime Permission from a thread other than the main thread, because you require it for some background work? If so, you can't. The mechanism implemented on the framework level requires user interaction, so it has to be connected to a UI - for example, the "Grant Permission" dialog box.

You don't have to call the permission-protected methods from an `OnClickListener` if you don't want to, that depends completely on your use case. However, be advised that it's generally considered a better user experience if Runtime Permissions are requested as a result of a user action, compared to simply requesting them in your Activity's `onCreate()`.
