### ISSUE TITLE
How to handle group permissions?

### ISSUE THREAD

**Issue by E3V3A** [hotchemi/PermissionsDispatcher#268]
We have a root based app that is using a large number of `dangerous` group permissions. So it seem quite unfeasible to implement every single permission by itself from [these groups](https://developer.android.com/guide/topics/permissions/requesting.html#perm-groups).  

- What is the best way to deal with this? 
- Can PD handle these? 

The particular permissions from each group are these:
````
Group           Permission (we need)
-----------------------------------------------------------------------
LOCATION        ACCESS_FINE_LOCATION, ACCESS_COARSE_LOCATION
PHONE           READ_PHONE_STATE, CALL_PHONE, USE_SIP, PROCESS_OUTGOING_CALLS
SMS             SEND_SMS, RECEIVE_SMS, READ_SMS, RECEIVE_WAP_PUSH, RECEIVE_MMS
STORAGE         READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE
````

**Comment by shiraji** [comment]
Have you tried listing them? like `@NeedsPermission({Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION, ...})`

**Comment by E3V3A** [comment]
Hi thanks for ultra-rapid feedback!
> Have you tried listing them?
I'm sure that works. But it would be more user friendly, if we could also write:
```
@NeedsPermission({Manifest.permission-group.LOCATION, Manifest.permission-group.PHONE, ...})
```

**Comment by shiraji** [comment]
What do you mean in terms of "user"?

**Comment by E3V3A** [comment]
@shiraji Sorry, I'm not trying to be a PITA here, just that the code would look much better and easier to read, if one doesn't have to list up every single permission, if one already knows what group they belong to.  If you think my case is too trivial, then please disregard my issus, but do add the question in a future FAQ or in your README as its not obvious how to best do this.

So given your response, the conclusion is that currently PD does not handle groups as separate entities (in case someone else is wondering about this.)

**Comment by shiraji** [comment]
Yes. PD doesn't support grouping. By the way, do you know AOSP support the "grouping"? (AFAIK, grouping only appear on the documentation, not in the code.) If so, PD will support it as soon as possible.

**Comment by aurae** [comment]
I also think that the classification of permissions in "groups" is merely a cosmetic one, and that you can't use them for framework-level Runtime Permissions. If I find time, I'll do a quick POC for that to check & verify, because it would be nice to support if you *could* actually do that.

**Comment by E3V3A** [comment]
> do you know AOSP support the "grouping"?

IDK. But I do know, if you on a AOS 6.0+ device, go to `Settings > apps > "some app" > permissions`, then what you see are these groups.

**Comment by E3V3A** [comment]
> 

I don't think this is cosmetic at all. Look [here](https://developer.android.com/guide/topics/security/permissions.html). But the way they are included into the AndroidManifest is non-trivial...
```
android:permissionGroup="android.permission-group.LOCATION"
android:permissionGroup="android.permission-group.PHONE"
android:permissionGroup="android.permission-group.SMS"
android:permissionGroup="android.permission-group.STORAGE"
```

By something like this: 
```xml
<uses-permission android:name="android.permission.INTERACT_ACROSS_USERS_FULL"
                     android:permissionGroup="android.permission-group.STORAGE"
                     android:protectionLevel="dangerous" />
```

**Comment by aurae** [comment]
After a quick exercise in Google-fu, I found [Mark Murphy's take on this](http://stackoverflow.com/a/30720740), which may be outdated at this point, but it makes a strong argument about the framework's Runtime Permissions model only handling `Manifest.permission.*`, as opposed to `Manifest.permission-group.*` as well. Since that seems to be the case, PermissionsDispatcher can't work around that.

**Comment by hotchemi** [comment]
@E3V3A Thx for your report.
In your case I suppose it's not bad to just asking one permission per each group. I know it's tricky but it can't be helped as that's the specification of Android Framework. And please make sure to asking each permission when it's actually needed([ref](https://developer.android.com/training/articles/user-data-permissions.html)).
About PermissionsDispatcher, we just generate handling code at compile time and delegate the work to it so I'm not for addressing `permission-group` constants. It might be handy in short run but  in the long run it will increase the maintenance cost of the app since user have to look into the library code when they encounter the problem.

**Comment by E3V3A** [comment]
@hotchemi, @aurae  and @shiraji  Again, thanks a lot for your support and explanations.

**Comment by hotchemi** [comment]
NP!

**Comment by E3V3A** [comment]
Reading the developer notes again: 

> If an app requests a dangerous permission listed in its manifest, and the app **already has another dangerous permission in the same permission group, the system immediately grants the [other] permission** without any interaction with the user. For example, if an app had previously requested and been granted the READ_CONTACTS permission, and it then requests WRITE_CONTACTS, the system immediately grants that permission. 

So I'm back to 4!
