### ISSUE TITLE
Polymorphism not supported?

### ISSUE THREAD

**Issue by lfdversluis** [hotchemi/PermissionsDispatcher#282]
## Overview

Having two methods with the same name but a different signature results in duplicate names in the generated files

### Expected

No errors

### Actual

Errors because of duplicate names

## Environment

- Which library version are you using? 2.3.1
- On which devices do you observe the issue? Nexus 4 / 5
- Note any other information that might be useful. Android 7

## Reproducible steps

Have two functions like this:

> 
> @NeedsPermission(Manifest.permission.ACCESS_FINE_LOCATION)
> public void showMapFragment() {
> 	Fragment fragment = StoresMapFragment.newInstance();
> 	showFragment(fragment);
> }
> 
> @NeedsPermission(Manifest.permission.ACCESS_FINE_LOCATION)
> public void showMapFragment(String json) {
> 	Fragment fragment = StoresMapFragment.newInstance();
> 	Bundle args = new Bundle();
> 	args.putString("a nice key", json);
> 	fragment.setArguments(args);
> 	showFragment(fragment);
> }

And it will generate variables like this (erroring) in the MainActivityPermissionDispatcher:

> 
> private static final int REQUEST_SHOWMAPFRAGMENT = 1;
> 
> private static final String[] PERMISSION_SHOWMAPFRAGMENT = new String[] {"android.permission.ACCESS_FINE_LOCATION"};
> 
> private static final int REQUEST_SHOWMAPFRAGMENT = 2;
> 
> private static final String[] PERMISSION_SHOWMAPFRAGMENT = new String[] {"android.permission.ACCESS_FINE_LOCATION"};

Which are the same, and thus error.

A workaround (for now) would be to give the function a different name.

**Comment by shiraji** [comment]
Interesting. Yes, this is not supported.

(By the way, it's method overloading, not polymorphism.)

**Comment by shiraji** [comment]
Not sure how to fix this problem. Maybe change the name of format? `PERMISSION_${METHOD_NAME}_${PARAMETER_TYPE}*`

WDYT @hotchemi @aurae ?

**Comment by lfdversluis** [comment]
Including the types of the objects should work. Also method overloading is a type of ad-hoc polymorphism, see https://en.wikipedia.org/wiki/Polymorphism_(computer_science) (although it is not well-defined anywhere and others argue otherwise)

**Comment by shiraji** [comment]
Good to know that!

**Comment by hotchemi** [comment]
@lfdversluis Thx for your suggestion.
IMO....`PERMISSION_${METHOD_NAME}_${PARAMETER_TYPE}*` is fine for defining permission constants, but on the other hand we need to give different names for each methods as well.
Like:

```java
static showMapFragmentStringWithCheck(Activity target) {
}
```

I'm just a bit anxious about this naming will make a debug or an understanding difficult, and this change would be a breaking change obviously so that we gotta be careful to decide.

What do you think folks?

**Comment by aurae** [comment]
Appending the parameter list to the generated static constants is OK with me, but I agree that the method signature naming could become a little tedious. If we used the simple class name of each parameter, the problem would simply be elevated one level above, e.g. with the following:

```java
package com.example.pkg1;
public class Model {}

package com.example.pkg2;
public class Model {}

package com.example;

@RuntimePermissions
public class AnActivity extends... {
    @NeedsPermission(...)
    void showMapFragment(com.example.pkg1.Model model) {
    }

    @NeedsPermission(...)
    void showMapFragment(com.example.pkg2.Model model) {
    }
}

package com.example;

final class AnActivityPermissionsDispatcher {
    static void showMapFragmentModelWithCheck(Activity target) {
        // Which one?
    }
}
```

I know, this is a convoluted example, but something to consider nonetheless. I think I'd prefer an additional compile-time check which prevents method overloading, rather than trying to include the parameters inside generated method names - which would also make refactoring a little more annoying.

**Comment by shiraji** [comment]
I agree with you guys. Changing method name could raise a lot of issues. And in most case, developer doesn't use method overloading. They don't get any benefit of that change.

For instance, In this case, code can be refactored like the following

```java
@NeedsPermission(Manifest.permission.ACCESS_FINE_LOCATION)
private void showMapFragment(Bundle bundle) {
    Fragment fragment = StoresMapFragment.newInstance();
    if (bundle != null) fragment.setArguments(args);
    showFragment(fragment);
}

public void showMapFragment() {
    showMapFragment(null);
}

public void showMapFragment(String json) {
    Bundle args = new Bundle();
    args.putString("a nice key", json);
    showMapFragment(bundle);
}
```

**Comment by lfdversluis** [comment]
@shiraji That looks like a reasonable approach. You do add additional functions, but it's not that bad. Looking at @aurae 's argument, I would say this might be the best approach (or if you really do not want additional functions, just name them differently).

Perhaps a few lines about this "issue" in the readme and it's all good and well?

**Comment by aurae** [comment]
In any case, we should implement that additional compile-time check, so that we help out the user as much as possible if they run into this - I'd rather have the compiler show a focussed error message detailing the issue with how PermissionsDispatcher is set up inside an Activity/Fragment, rather than the generated code itself not compiling and blowing up. It's in line with the existing checks we have in place, and provides a better experience overall.

**Comment by hotchemi** [comment]
Thank you guys! Let me close the issue and move on #283 .
