### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BigKarel** [hotchemi/PermissionsDispatcher#302]
When i get permission， open the app permissions setting，turn off this permission，return to the application home page，the crash occurred.

video：
[WeChatSight6.mp4.zip](https://github.com/hotchemi/PermissionsDispatcher/files/946762/WeChatSight6.mp4.zip)

**Comment by shiraji** [comment]
Could you convert mp4 to gif? and post it here?

**Comment by aurae** [comment]
Looking at your video, this is the expected behaviour, as far as I can tell from the Chinese UI. When you revoke permission to use the camera, then return to the app, the camera view is not showing anymore until the user grants permission again. This is a wontfix as far as I'm concerned, unless I'm missing your point.

**Comment by hotchemi** [comment]
@BigKarel as @aurae mentioned the camera behavior from your video is expected(I wanna clarify what `the crash occurred.` is pointing out though).
But I just found another crash about contact list while I was reproducing the problem. This is a bug of our sample app and it'd be better to fix that.
Anyway thx for your report!

**Comment by BigKarel** [comment]
thx
