### ISSUE TITLE
Remove a workaround for targetSdkVersion < 23

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#305]
## Overview

- Currently we have a workaround that checks `PermissionUtils.getTargetSdkVersion(target) < 23` to make sure that the library works under Marshmallow device.
- This feature is requested by a few user initially, but it's over one and a half year since the library came out so it's okay to remove this workaround to avoid unnecessary check for most of user.

```java
    static void onRequestPermissionsResult(MainActivity target, int requestCode, int[] grantResults) {
        switch (requestCode) {
            case REQUEST_SHOWCAMERA:
                if (PermissionUtils.getTargetSdkVersion(target) < 23 && !PermissionUtils.hasSelfPermissions(target, PERMISSION_SHOWCAMERA)) {
                    target.onCameraDenied();
                    return;
                }
                if (PermissionUtils.verifyPermissions(grantResults)) {
                    target.showCamera();
                } else {
                    if (!PermissionUtils.shouldShowRequestPermissionRationale(target, PERMISSION_SHOWCAMERA)) {
                        target.onCameraNeverAskAgain();
                    } else {
                        target.onCameraDenied();
                    }
                }
                break;
            default:
                break;
        }
    }
```

**Comment by aurae** [comment]
I feel like, at this point, we can force our users to use a `targetSdkVersion` of at least 23. I'm interested whether we can check this in the annotation processor, actually. I'd like to raise an Exception on lower Target SDK levels, just because we can avoid users opening issues regarding a regression in support.

**Comment by hotchemi** [comment]
Umm, I'd say it's a bit strong restriction. 
The reason of checking getTargetSdkVersion is to deal with the case that user turn off a permission from setting page on under Marshmallow device, but I think it's too rare case to take care.
In other words about 99% case PermissionsDispatcher assures the correct action even if taretSdkVersion is lower than 23. Thus showing a caution message or something is fine for sure 😺

**Comment by aurae** [comment]
Ah, I see now. However, if we keep this conditional logic anyway (to show the "caution message" you're referring to, for instance), why not just keep the current functionality? I agree that we can could clean up the generated code here if we removed the `targetSdkVersion` check, but if we just remove the behavior and keep the conditional, I'd prefer the current way.

**Comment by hotchemi** [comment]
Well, of course we can keep that but `getTargetSdkVersion` method accesses to package manager and parse the manifest file so it's not a light method I guess. And another reason is that it's been a long time since Marshmallow being out so it's not early to encourage user to update targetSdkVersion to 23:D
If user stick to older version they can use older ver of PermissionsDispatcher, the library is already matured so it's not a cruel attitude to conservative user.

**Comment by aurae** [comment]
I completely agree with you, especially since we've arrived at Target SDK ´26` by now! That was my motivation regarding https://github.com/hotchemi/PermissionsDispatcher/issues/305#issuecomment-298186940, which we can use to clean up the generated code. If a user really wants to stay at 22 or lower (for reasons unknown), they can use the current stable version. Going forward, we would then present the "caution message" during compile-time. It doesn't have to be a build-failing error - a warning would be just fine. Again, we would have to find out if we can get the current Target SDK from inside the annotation processor, because I don't know.

**Comment by SolveSoul** [comment]
Is there any action needed for this? My project can't build anymore throwing exactly this error:

> Error:(50, 26) error: cannot find symbol method getTargetSdkVersion(PermissionsActivity)

My targetSdkVersion is set to 25 and my Gradle has the following included: 
`compile 'com.github.hotchemi:permissionsdispatcher:2.4.0'`

**Comment by hotchemi** [comment]
you should add runtime module as compile dependency.

```
 compile 'com.github.hotchemi:permissionsdispatcher:2.4.0'
```
