### ISSUE TITLE
Add android.app.Fragment support

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#31]
Picasso or Retrofit's implementation are very useful for us I guess.

**Comment by aurae** [comment]
The support is already integrated into 2.0.0; I'll do a quick write-ups of how the optional dependency works!

**Comment by hotchemi** [comment]
@aurae 
Actually I wanna re-consider the api interface.
In my think, resolving the problem by checking support v13 existence may causes the problem.
I mean, some app use `android.appFragment` and `support.v4.Fragment` at the same time.

**Comment by aurae** [comment]
I think that it would be an even better API if the user didn't have to deal with PermissionsDispatcher's configuration when it comes to fragments.

Here is how it works in the new Kotlin architecture:

* PermissionsDispatcher is supported on API levels 4+, since it depends on `support-v4` because of its `ActivityCompat` usage
* Because of that, the library supports `Activity` and `support.v4.Fragment` out of the box, without any extra dependencies
* Now, if someone used native Fragments in their app with PermissionsDispatcher, they may get the following error on compilation: `permissions.dispatcher.processor.exception.SupportV13MissingException: PermissionsDispatcher for annotated class 'MyNativeFragment' can't be generated, because the support-v13 dependency is missing on your project`
* To resolve this, the user just needs to drop in a dependency on `support-v13` alongside PermissionsDispatcher, and their native fragments will become supported as well! This doesn't mean that `support.v4.Fragment` isn't supported anymore, it is simply another functionality on top of that, so they could technically use both types of Fragment at the same time

I don't think it's necessary to have the user deal with which configuration PermissionsDispatcher should use.

**Comment by hotchemi** [comment]
Oh sorry, I've not seen your PR well, please just a minute.

**Comment by aurae** [comment]
It's all good. Take your time!
