### ISSUE TITLE
Why is there a limitation that I cannot return any value from the annoted method?

### ISSUE THREAD

**Issue by ankitrg** [hotchemi/PermissionsDispatcher#312]
I want to permissions for Storage and I am returning a file path after storing it. Is there a way to achieve this?

**Comment by aurae** [comment]
You can't use a return value in methods annotated with `@NeedsPermission` because of the asynchronous nature of the Runtime Permissions model. When you call that method, you don't know if you've already been given permission or not - if you don't, then PermissionsDispatcher has to "get back to you" at a later time, depending on whether the user granted permission or not.

Your use case would typically be achieved by performing the critical operation inside a wrapping method that returns `void` and is annotated:

```java
@RuntimePermissions
public class YourActivity extends AppCompatActivity {
    void someListenerOrOtherMethod() {
        YourActivityPermissionsDispatcher.accessStorageWithCheck(this);
    }

    @NeedsPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
    void accessStorage() {
        // Do the operation here, don't annotate storeObjectAndReturnFilePath() itself!
        Uri storedPath = storage.storeObjectAndReturnFilePath(object);

        // Do something with the Uri
        // ...
    }

    // onActivityResult() etc. omitted...
}
```
