### ISSUE TITLE
[Question] Expected behavior for multiple permission

### ISSUE THREAD

**Issue by fchauveau** [hotchemi/PermissionsDispatcher#313]
Hello.

I'm using requesting two premissions for one method call
`@NeedsPermission({Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE})`
But even if camera is already granted, the system dialog ask for the two permissions.

So from your point of view is it the expected behavior ? 

Thx.

**Comment by hotchemi** [comment]
@fchauveau thx for your interest. We just call `Activity/FragmentCompat.requestPermisssions` inside the library to improve traceability for debugging.
So it's the expected behavior. If you wanna address the problem as such we recommend to separate methods per each permission.

ref: https://github.com/hotchemi/PermissionsDispatcher/issues/69#issuecomment-170479640

**Comment by fchauveau** [comment]
okay thx for the quick response.

**Comment by hotchemi** [comment]
@fchauveau my pleasure!
