### ISSUE TITLE
Error:Module 'com.github.hotchemi:permissionsdispatcher:2.4.0' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by zhaocheng19940105** [hotchemi/PermissionsDispatcher#315]
Error:Module 'com.github.hotchemi:permissionsdispatcher:2.4.0' depends on one or more Android Libraries but is a jar 
     compile 'com.github.hotchemi:permissionsdispatcher:2.4.0'
    annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.4.0'

**Comment by aurae** [comment]
Are you using Jitpack dependencies? If so, it probably tries to resolve the dependency on PD before `jcenter()` can. Since the repositories available to projects are checked in order, please move Jitpack's repo below jcenter to get rid of this issue.

@hotchemi @shiraji We should consider switching the artifact's group to avoid clashing with Jitpack.

**Comment by hotchemi** [comment]
@aurae @shiraji Thx! not sure it's possible to switching the artifact's group though🤔
