### ISSUE TITLE
Asks for already granted permissions

### ISSUE THREAD

**Issue by markini** [hotchemi/PermissionsDispatcher#32]
I have 2 methods, both need multiple permissions:

```java
@NeedsPermissions({WRITE_EXTERNAL_STORAGE, RECORD_AUDIO})
void recordAudio() { ... }

@NeedsPermissions({WRITE_EXTERNAL_STORAGE, CAMERA})
void takePhoto() { ... }
```

Even after granting the `WRITE_EXTERNAL_STORAGE` permission at the first method, the app still asks about this permission at the second method.

**Comment by hotchemi** [comment]
I think this is the default implementation of android framework.

The library just calls [ActivityCompat.requestPermissions](http://developer.android.com/reference/android/support/v4/app/ActivityCompat.html#requestPermissions(android.app.Activity, java.lang.String[], int)). Please see the generated code.

**Comment by aurae** [comment]
This is definitely interesting. Have you filed an issue on the AOSP bug tracker yet? This doesn't seem to be working as intended; however, as @hotchemi already said, we are kinda at the mercy of the framework here, since we rely solely on the framework, and PermissionsDispatcher simply provides a nicer interface to working with that.

**Comment by kcoppock** [comment]
I think you should be wrapping the check on `ActivityCompat.requestPermissions()` in checks for `ContextCompat.checkSelfPermission()` as well, to make sure the permissions haven't already been granted. `ActivityCompat.requestPermissions()` will *always* request permission, even if you already have it, to my knowledge.

**Comment by hotchemi** [comment]
@kcoppock Of course we do it. Please see generated code.

**Comment by hotchemi** [comment]
@markini @aurae 
I understand why it happens.
When you try to handle multiple permissions at once, library checks all of permissions have been granted or not with [PermissionUtils](https://github.com/hotchemi/PermissionsDispatcher/blob/master/permissionsdispatcher/src/main/android/permissions/dispatcher/PermissionUtils.java#L38).
And if there is one or more not granted permission, we have to call requestPermissions with the argument of `@NeesPermissions`. So that's why it happens.
To avoid that, you can use multiple `NeedsPermission` at the different timing. 
But in my think, it's worth to ask users because app may use same permissions for the different purpose.

**Comment by aurae** [comment]
According to [this AOSP issue](https://code.google.com/p/android-developer-preview/issues/detail?id=2966), asking for an already granted permission is intended behaviour. We could filter out all permissions from the `String[]` signature that had been granted before and call `requestPermissions()` with only those, however I feel like this should be an opt-in behaviour, since being able to "ask again" seems to be desired by the Android team.

**Comment by hotchemi** [comment]
That's exactly. We can filter but is it worth? My opinion is "No" and we should follow the default behaviour of framework.
Really appreciate for your report @markini .
