### ISSUE TITLE
Kotlin. Internal WithCheck method generation

### ISSUE THREAD

**Issue by horse315** [hotchemi/PermissionsDispatcher#327]
Hi!
After I migrated my project to Kotlin, ```internal``` methods with ```@NeedsPermission``` annotation are generated with internal Kotlin names and look like this:
```
MainActivity2PermissionsDispatcher.`showCamera$sample_kotlin_debugWithCheck`(this)

MainActivity2PermissionsDispatcher.`showContacts$sample_kotlin_debugWithCheck`(this)
```
I had to make all these methods public.
Do you have a better solution?

**Comment by horse315** [comment]
Also, ```PermissionsDispatcher``` class is not generated at the right time and module build fails. I had to comment all ```PermissionsDispatcher``` references, build the module and uncomment them back. Such behavior brakes straight CI module build.
I've prepared a sample to investigate: ```sample-kotlin``` https://github.com/horse315/PermissionsDispatcher

**Comment by hotchemi** [comment]
@horse315 thx for your adopting!
Actually that's one of our [known issue](https://github.com/hotchemi/PermissionsDispatcher/blob/master/doc/known_issues.md), Kotlin `internal` keyword bundles weird info to annotation processing env so that method name becomes weird as well.
The most approachable way for now is just removing `internal` keyword from `@NeedsPermission` method. We'll plan to deal with the issue but not decided where to accomplish 🙇

ref: https://github.com/hotchemi/PermissionsDispatcher/issues/171

**Comment by horse315** [comment]
@hotchemi any ideas about kotlin module build order? How can I bump annotation processor?

**Comment by hotchemi** [comment]
@horse315 No problem! We'll address this problem in the near future, hopefully:D

**Comment by hotchemi** [comment]
This issue will be resolved with #320 .

**Comment by hotchemi** [comment]
@horse315 now you can test with `3.0.0-SNAPSHOT`!

**Comment by horse315** [comment]
@hotchemi, it works great, thanks!
