### ISSUE TITLE
Can This Lib work in a background Service?

### ISSUE THREAD

**Issue by ThanosFisherman** [hotchemi/PermissionsDispatcher#34]
Hello, that's my question pretty much. I need to check for location permissions in my background service so I thought this lib could save me a lot of time (and code).

**Comment by aurae** [comment]
Requesting a Runtime Permission is currently not possible from a Service, since `requestPermissions()` is available only from `Activity` and the two flavors of `Fragment`. This is a limitation imposed by the framework.

The common practice how to approach this would be to check for the permission in your Service using our `PermissionUtils.hasSelfPermission()` method (since that only requires a `Context`), and if you haven't been granted the Location permission, you fire a notification to the device's notification bar, which redirects to an Activity from which you can then request the permission.

**Comment by ThanosFisherman** [comment]
Damn that new permission system is making my life harder. But Thank you @aurae that's actually a good idea. I'm going to implement it just like that. Cheers!

**Comment by hotchemi** [comment]
Yeah that's the problem for official android mechanism.
You can also use `PermissionChecker` in support v4 library.

**Comment by thuan09878** [comment]
Can I use this lib in JobIntentService now in 2018?

**Comment by hotchemi** [comment]
@thuan09878 you should handle permission before running `JobIntentService`. It's Activity or Fragment responsibility.
