### ISSUE TITLE
READ_EXTERNAL_STORAGE broken on API 15 device

### ISSUE THREAD

**Issue by robinstark** [hotchemi/PermissionsDispatcher#51]
This will also apply to other permissions that were only introduced in newer Android versions than the app is running on.

A method in my app requires READ_EXTERNAL_STORAGE permission, but this permission was only introduced in API 16. When running the generated ...WithCheck() method on an API 15 device, PermissionsUtils.hasSelfPermissions will never return true (since the READ_EXTERNAL_STORAGE permission doesn't exist), and so the target method will never get called - even though the app will run fine without that permission. PermissionsDispatcher acts as if the permission has been denied.

I'm working around it with
```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
    MyActivityPermissionsDispatcher.doThingWithCheck(this);
} else {
    doThing();
}
```

but that feels broken and it would be much cleaner if I didn't have to.

**Comment by aurae** [comment]
This behaviour occurs because of an architectural decision in the Android framework, where non-existent permissions are never granted by design. I see the point about performing conditional checks on certain permissions that were added later in the Android lifecycle. This would most likely be enforceable in `PermissionsUtils` using a static mapping of those permissions to their minimum SDK level.

Mark Murphy published [a great article](https://commonsware.com/blog/2015/11/09/you-cannot-hold-nonexistent-permissions.html) on the exact same issue on his blog recently.

**Comment by robinstark** [comment]
Awesome, thanks. I'll look forward to 2.0.1. My workaround feels like a bit too much of a blunt instrument, applying checks specifically to the permissions and devices that need them is a much better idea.

**Comment by aurae** [comment]
This is what my sketch looks like at the moment:

```java
public final class PermissionUtils {

    // Map of dangerous permissions introduced in later framework versions.
    // Used to conditionally bypass permission-grant checks on older devices.
    private static final SimpleArrayMap<String, Integer> MIN_SDK_PERMISSIONS;
    static {
        MIN_SDK_PERMISSIONS = new SimpleArrayMap<>(6);
        MIN_SDK_PERMISSIONS.put("com.android.voicemail.permission.ADD_VOICEMAIL", ICE_CREAM_SANDWICH);
        MIN_SDK_PERMISSIONS.put("android.permission.BODY_SENSORS", KITKAT_WATCH);
        MIN_SDK_PERMISSIONS.put("android.permission.READ_CALL_LOG", JELLY_BEAN);
        MIN_SDK_PERMISSIONS.put("android.permission.READ_EXTERNAL_STORAGE", JELLY_BEAN);
        MIN_SDK_PERMISSIONS.put("android.permission.USE_SIP", GINGERBREAD);
        MIN_SDK_PERMISSIONS.put("android.permission.WRITE_CALL_LOG", JELLY_BEAN);
    }

    // ...

    private static boolean permissionExists(String permission) {
        // Check if the permission could potentially be missing on this device
        Integer minVersion = MIN_SDK_PERMISSIONS.get(permission);

        // If null was returned from the above call, there is no need for a device API level check for the permission;
        // otherwise, we check if its minimum API level requirement is met
        return minVersion == null || Build.VERSION.SDK_INT >= minVersion;
    }

    /**
     * Returns true if the Activity or Fragment has access to all given permissions.
     *
     * @param context     context
     * @param permissions permission list
     * @return returns true if the Activity or Fragment has access to all given permissions.
     */
    public static boolean hasSelfPermissions(Context context, String... permissions) {
        for (String permission : permissions) {
            if (!permissionExists(permission) || checkSelfPermission(context, permission) != PackageManager.PERMISSION_GRANTED) {
                return false;
            }
        }
        return true;
    }
}
```

I think that this should solve your issue. It basically lets `hasSelfPermissions` pass every check to a permission that was added in a later SDK version on devices below that minimum requirement. I'm not too sure about the copy-pasted values from `Manifest.permission`, however I don't think we can reference those directly here since, you know, these constants are missing on old-enough devices.

**Comment by robinstark** [comment]
Looks good, thanks very much.

About the constants - my API 15 device got the right value for `READ_EXTERNAL_STORAGE` even though it didn't know what to do with it, so I suspect they'd be fine to use so long as PD is always being compiled with the latest SDK (to cover permissions added in future API levels). If someone wants to use a new permission introduced in a future SDK, they'll be using that SDK so it should all work out. But then again, it could be good to just capture the actual values now, rather than having to worry about API levels at all. Probably either decision is fine!

**Comment by sibeliusseraphini** [comment]
@aurae I've tested your code in some older devices and it is working
