### ISSUE TITLE
[question] remove delegate permission dispatcher

### ISSUE THREAD

**Issue by sibeliusseraphini** [hotchemi/PermissionsDispatcher#56]
I wonder whether it is possible to remove the delegate pattern used in this lib, and make even easier to handle permissions

**Comment by aurae** [comment]
What would you suggest instead?

**Comment by sibeliusseraphini** [comment]
When we call a method annotated @NeedsPermission, it should call MainActivityPermissionsDispatcher.methodWithCheck(this) instead.

But I don't know whether it is easy or possible to code this

**Comment by aurae** [comment]
I'm afraid that this isn't really possible, since that would require byte code manipulation of method invocations, which is beyond the scope of both us and the library. However, now that I think about it, we may look into creating custom lint rules for the library, so that your IDE shows a warning when you're calling an annotated method directly, potentially with a quick fix to change the code to the correct method on the delegate object.

**Comment by hotchemi** [comment]
I don't like this idea.
We can do that when we manipulate byte code but why we have to do that?
The purpose of annotation processing is to delegate the work to generated class.

**Comment by aurae** [comment]
I do think that preventing users from accidentally calling permission-protected code directly should be something we need to consider. Using Lint to raise warnings (or even errors) when people bypass the "delegate call chain" should be on our radar.

**Comment by aurae** [comment]
This discussion will be moved to #59.

**Comment by sibeliusseraphini** [comment]
@aurae thanks
