### ISSUE TITLE
Multiple Permission Request Issue

### ISSUE THREAD

**Issue by androidyue** [hotchemi/PermissionsDispatcher#69]
Now I am using PermissionsDispatcher and write the following code
```
@NeedsPermission({Manifest.permission.READ_PHONE_STATE, Manifest.permission.WRITE_EXTERNAL_STORAGE})
    public void useDeviceId() {
        TelephonyManager telephonyManager = (TelephonyManager)getSystemService(Context.TELEPHONY_SERVICE);
        String deviceId = telephonyManager.getDeviceId();
        Log.i(LOGTAG, "useDeviceId deviceId=" + deviceId);
    }
```
When you call the method `MainActivityPermissionsDispatcher.useDeviceIdWithCheck()`
This will request two permissions at once.  There are two permission in the dialog.  And then you grant the first and deny the second. 

Once again you call the method `MainActivityPermissionsDispatcher.useDeviceIdWithCheck()` the two permissions are still including the already-granted permission.  This should be improved, only the denied permission should be in the dialog.

For better understanding, I did a demo, see this repo. https://github.com/androidyue/PermissionsDispatcherMutiplePermissionIssue

or use this apk:http://7u2rgp.com1.z0.glb.clouddn.com/multiple-permission-issue.apk

**Comment by aurae** [comment]
While I do agree that it would make sense for the dialog to only request the permission the user didn't already grant, this is working as intended based on the implementation of runtime permissions in the Android platform. Until there is more customizability for how apps show system dialogs for multi-permission requests (i.e. so that you could specify "either accept all, or deny all"), there's nothing that can be done about the behaviour that PermissionsDispatcher provides, since we're merely exposing a more convenient interface to the framework.
