### ISSUE TITLE
Doesn't work with kotlin 1.0.0-rc-1036

### ISSUE THREAD

**Issue by swissonid** [hotchemi/PermissionsDispatcher#89]
My App doesn't start any more. It can't find the ApplicationClass

**Comment by hotchemi** [comment]
Sorry, could u give us more detail information?

**Comment by mosberger** [comment]
In Kotlin Version 1.0.0-rc-1036, the annotation interface has changed and the method annotationType() does no longer exist.
We've tried to fix this with the when clause from kotlin, but this breaks the PERMISSIONS array in the generated PermissionsDispatcher file.
Here are the changed files:
- [Extensions.kt](https://github.com/swissonid/PermissionsDispatcher/blob/2b843edf92ca07f68fcff987a92ee6d59d54e5d3/processor/src/main/kotlin/permissions/dispatcher/processor/util/Extensions.kt)
- [DuplicatedValueException.kt](https://github.com/swissonid/PermissionsDispatcher/blob/2b843edf92ca07f68fcff987a92ee6d59d54e5d3/processor/src/main/kotlin/permissions/dispatcher/processor/exception/DuplicatedValueException.kt)
- [NoAnnotatedMethodsException.kt](https://github.com/swissonid/PermissionsDispatcher/blob/2b843edf92ca07f68fcff987a92ee6d59d54e5d3/processor/src/main/kotlin/permissions/dispatcher/processor/exception/NoAnnotatedMethodsException.kt)
- [PrivateMethodException.kt](https://github.com/swissonid/PermissionsDispatcher/blob/2b843edf92ca07f68fcff987a92ee6d59d54e5d3/processor/src/main/kotlin/permissions/dispatcher/processor/exception/PrivateMethodException.kt)

**Comment by aurae** [comment]
This library hasn't been verified against the latest Kotlin RC yet. The folks over at JetBrains have made significant changes to the way that Kotlin operates on several levels, including the bytecode level, which is why they are demanding that code using earlier builds of the language be recompiled. That may already fix your issue, however we have to make sure that the APIs used by the processor are still available on the latest version.

**Comment by hotchemi** [comment]
@swissonid Could u squash commits? After that I'm gonna merge it.
